module.exports = {
  apps: [
    {
      name: 'hailo-camera',
      script: 'server.js',
      cwd: __dirname,
      env: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || 3001,
        AUTH_TOKEN: process.env.AUTH_TOKEN || '',
        CORS_ALLOW_ALL: process.env.CORS_ALLOW_ALL || '',
        CORS_ORIGIN: process.env.CORS_ORIGIN || '',
        ANALYZE_URL: process.env.ANALYZE_URL || 'http://127.0.0.1:3000/api/analyze/from-file',
        DEFAULT_WIDTH: process.env.DEFAULT_WIDTH || '',
        DEFAULT_HEIGHT: process.env.DEFAULT_HEIGHT || '',
        DEFAULT_FPS: process.env.DEFAULT_FPS || '',
        DEFAULT_STILL_DURATION_SEC: process.env.DEFAULT_STILL_DURATION_SEC || '',
        DEFAULT_VIDEO_DURATION_SEC: process.env.DEFAULT_VIDEO_DURATION_SEC || '',
        HAILO_MODEL_NAME: process.env.HAILO_MODEL_NAME || 'yolov8n_service7',
        HAILO_MODEL_ALIASES: process.env.HAILO_MODEL_ALIASES || 'yolov8n_service7,yolov8s',
        HAILO_HEF_PATH: process.env.HAILO_HEF_PATH || "/usr/share/hailo-models/yolov8n_service7_960.hef",
        HAILO_INFERENCE_WIDTH: process.env.HAILO_INFERENCE_WIDTH || '960',
        HAILO_INFERENCE_HEIGHT: process.env.HAILO_INFERENCE_HEIGHT || '960',
        HAILO_POSTPROCESS_LIB: process.env.HAILO_POSTPROCESS_LIB || 'libyolo_hailortpp_post.so',
        HAILO_POSTPROCESS_FUNC: process.env.HAILO_POSTPROCESS_FUNC || 'yolov8s',
        HAILO_PREVIEW_POSTPROCESS_FUNC: process.env.HAILO_PREVIEW_POSTPROCESS_FUNC || 'filter',
        AI_POSTPROCESS_CONFIG: process.env.AI_POSTPROCESS_CONFIG || '/home/ray/hailo-camera/config/yolov8n_service7_nms.json',
        SESSION_LABEL_MAP: process.env.SESSION_LABEL_MAP || '0:person,1:player_ready,2:player_not_ready,3:golf_ball,4:club_head,5:club,6:club_handle',
        GST_PLUGIN_PATH: "/lib/aarch64-linux-gnu/gstreamer-1.0:/usr/lib/aarch64-linux-gnu/gstreamer-1.0",
        LD_LIBRARY_PATH: "/usr/lib/aarch64-linux-gnu/hailo/tappas/post_processes:/usr/lib/aarch64-linux-gnu:/usr/lib",
      },
    },
  ],
};
